# Generated by Django 2.0.2 on 2018-12-14 15:25

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='richcontent',
            field=mdeditor.fields.MDTextField(default=''),
        ),
    ]
