# Generated by Django 2.0.2 on 2018-12-14 15:27

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_richcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='richcontent',
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=mdeditor.fields.MDTextField(default=''),
        ),
    ]
