# Generated by Django 2.0.2 on 2018-12-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(default='201812071452039100', editable=False, max_length=18, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=50)),
                ('goods_amount', models.IntegerField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('arrive_time', models.DateTimeField()),
                ('order_status', models.BooleanField(default=False)),
                ('ship_use', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipmanage.Ship')),
            ],
        ),
        migrations.AlterField(
            model_name='berth',
            name='berth_used',
            field=models.IntegerField(max_length=20),
        ),
    ]
