# Generated by Django 2.0.2 on 2018-12-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0005_auto_20181214_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812142337313222', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
