# Generated by Django 2.0.2 on 2018-12-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0006_auto_20181214_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berth',
            name='berth_used',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='goods_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812142339167258', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
