# Generated by Django 2.0.2 on 2018-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0007_auto_20181214_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_owner',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812200004506057', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
