# Generated by Django 2.0.2 on 2018-12-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0008_auto_20181220_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='target_port',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812200019574631', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
