# Generated by Django 2.0.2 on 2018-12-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0009_auto_20181220_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrive_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812200023479418', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
