# Generated by Django 2.0.2 on 2018-12-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0013_auto_20181228_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='url_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='ship',
            name='url_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812280018367394', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
