# Generated by Django 2.0.2 on 2018-12-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0014_auto_20181228_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ship_capacity',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812280022596369', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
