# Generated by Django 2.0.2 on 2018-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0016_auto_20181228_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812280029529520', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
