# Generated by Django 2.0.2 on 2018-12-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipmanage', '0017_auto_20181228_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ship_owner',
            field=models.CharField(default='PLIS', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='201812281723225906', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
    ]
