# Generated by Django 2.0.2 on 2018-11-06 05:10

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCode',
            fields=[
                ('code', models.CharField(default=login.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('is_new', models.BooleanField(default=True, editable=False)),
            ],
        ),
    ]
